### ISSUE TITLE
Bug: using scrolls in any level after the first one crashes the game

### ISSUE THREAD

**Issue by gbrunofranco** [SelinaDev/Godot-Roguelike-Tutorial#12]
Whenever you use any scroll on any level after the first one results in the game crashing due to the fact that `item` has stale `map_data` and tries to act on freed instances of tiles/entities.

To fix the issue I added the following line in the `activate_item` function in `main_game_input_handler.gd`

`selected_item.map_data = player.map_data`

In this way we ensure that the item has the same `map_data` as the player, which we update in `generate_dungeon`. Another possibility would be to iterate over every item and update its `map_data` in `generate_dungeon` as well.

**Comment by SelinaDev** [comment]
Thank you for bringing this to my attention! I just noticed something like this with the confusion scroll (after reloading a game in my case), and already fixed it there. I overlooked that for the other items. Should be fixed by a79deb9
