### ISSUE TITLE
Part 2:  "You should now be able to run the project and see two characters at the center of the screen" (you can't)

### ISSUE THREAD

**Issue by rosskarchner** [SelinaDev/Godot-Roguelike-Tutorial#16]
Hello! I'm enjoying the tutorial so far.

Unless I've missed something, when you hit the statement "You should now be able to run the project and see two characters at the center of the screen", you actually can't yet, because `_process` hasn't been updated or replaced yet, and still contains references to the now-deleted `player_grid_pos`.

**Comment by rosskarchner** [comment]
Taking another look, and I think the problem is that when you say "Modify the top of the script to read as follows", I didn't occur to me that I should remove `_process`, since I was just "modifying the top". 

So, maybe just a reading comprehension issue on my part, but it might be clearer to just say "replace the contents of game.gd with this"

**Comment by SelinaDev** [comment]
I updated part 2 of the tutorial now, according to your recommendations. I mentioned removing the `_process()` function, and added a few sentences explaining Godot's render order. I have something like this in a later tutorial, where a similar problem was common, but I didn't realize this could be a problem in part 2 as well. I think this explanation should provide valuable context. Thank you again.
