### ISSUE TITLE
Part 10,  hp_display.gd

### ISSUE THREAD

**Issue by rosskarchner** [SelinaDev/Godot-Roguelike-Tutorial#18]
I got through part 10, but noticed that my HP display had stopped working. It looks like you made some changes to hp_display.gd that aren't referenced in the actual tutorial. Once I made the change, it worked.

```sh
$ diff part_9/src/GUI/hp_display.gd part_10/src/GUI/hp_display.gd 
8c8,9
< 	await ready
---
> 	if not is_inside_tree():
> 		await ready
```

**Comment by SelinaDev** [comment]
Thank you for mentioning this, I will update the tutorial soon!

**Comment by SelinaDev** [comment]
I just uploaded a version of part 10 that includes a mention of this.
