### ISSUE TITLE
Part 13

### ISSUE THREAD

**Issue by rosskarchner** [SelinaDev/Godot-Roguelike-Tutorial#20]
I'm done! Thanks again for the tutorial.

Here are two problems I found in part 13:

- This section isn't in the written tutorial:  https://github.com/SelinaDev/Godot-Roguelike-Tutorial/blob/main/part_13/src/Entities/entity.gd#L72C1-L77C67
- when you say "If you start the game now you should be able to go into the inventory and select these items.", you can't actually do that yet, because the `await _player.ready` fix in `update_labels` needs to happen before you can create a new game.

**Comment by rosskarchner** [comment]
One more (sorry!), I don't see any mention of the changes to these functions, where the level up code modifies base_power or base_defense, instead of power or defense:  https://github.com/SelinaDev/Godot-Roguelike-Tutorial/blob/main/part_13/src/Entities/Actors/Components/level_component.gd#L55-L68

**Comment by rosskarchner** [comment]
Here's one more: the `leveled_up` signal is never emitted in your code, which means the character attributes don't appear to change (even if they really do)

**Comment by rosskarchner** [comment]
Glad it's helpful! One thing I experienced while playing, but haven't dug into how to fix yet:  if you use the keyboard to activate an inventory item that happens to be assigned the "v" hotkey, that also triggers the "look" functionality(reticle). It seems like that shouldn't be the case,  but maybe I'm missing something.

**Comment by rosskarchner** [comment]
I'm still confused about *why* that was happening-- but I had v mapped to both "look" and "view history", and fixing "look" to match your version of the project fixed my issue, so ¯\_(ツ)_/¯

**Comment by SelinaDev** [comment]
Sorry it took me so long to get around to working on the tutorial again, but I finally went over your suggestions and added the missing parts to tutorial 13.
