### ISSUE TITLE
Levelling up doesn't update display

### ISSUE THREAD

**Issue by LiamBull** [SelinaDev/Godot-Roguelike-Tutorial#22]
Hello,

Noticed a small bug in the `increase_level()` function in `level_component.gd`.

It is missing a call to emit the `leveled_up` signal, which is what the `CharacterInfoBox` connects to to update the labels.

Can be fixed by adding `leveled_up.emit()` to the function.

**Comment by LiamBull** [comment]
Opened a PR to fix it: https://github.com/SelinaDev/Godot-Roguelike-Tutorial/pull/23

**Comment by SelinaDev** [comment]
Thank you so much. I'm sorry it took so long, but I just merged your PR and updated the code in the tutorial itself.
