### ISSUE TITLE
XP Changed is not emitted during level up

### ISSUE THREAD

**Issue by onishounen** [SelinaDev/Godot-Roguelike-Tutorial#25]
Similar to #23. In the `increase_level()` function, the XP bar is not updated when the XP is reset. I believe this can be easily fixed by updating this function as follows:

```
        current_xp -= get_experience_to_next_level()
	current_level += 1
	xp_changed.emit(current_xp, get_experience_to_next_level())
	leveled_up.emit()
````

**Comment by SelinaDev** [comment]
Thank you for mentioning this, and thank you for your patience. Today I finally got the chance for some bug fixing and revisions.
I added that code to part 11 and following, and added the code and a mention of it in the written tutorial.
