### ISSUE TITLE
bug with confused spell at part 9

### ISSUE THREAD

**Issue by Devengel** [SelinaDev/Godot-Roguelike-Tutorial#7]
`
func perform() -> void:
	if turns_remaining <= 0:
		MessageLog.send_message("The %s is no longer confused.", Color.WHITE)
		entity.ai_component = previous_ai
		queue_free()
`

the %s  part is not written, it is missing entity.get_entity_name()

**Comment by thedyze** [comment]
Confirmed. 

confused_enemy_ai_component.gd, perform() function should be updated with:

MessageLog.send_message("The %s is no longer confused." % entity.get_entity_name(), Color.WHITE)

**Comment by SelinaDev** [comment]
Thank you for notifying me. I just uploaded the changes both in this repository and the turorial.
